### ISSUE TITLE
HiCAT

### ISSUE THREAD

**Issue by duhuipeng** [xjtu-omics/HiCAT#1]
Dear author
Could you share the code of these two pictures？
![image](https://user-images.githubusercontent.com/58722433/206658028-7bb71f22-4c9b-4f74-b655-98f9723afce4.png)
![image](https://user-images.githubusercontent.com/58722433/206658214-bc30df43-faab-4ffd-a3ed-7475267c9207.png)
Best
HuipengDu

**Comment by yangxiaofeill** [comment]
Hi Huipeing, 
    The dotplot is generated by Gepard [https://github.com/univieCUBE/gepard]
    The barplot is plotted by python, and the code is

```
file = 'out_hor.normal.fa' # input HOR fa
target_pattern = 'R3L6'
outfile = target_pattern+'.pdf' # outfile

dis_table = {}
rHORs = set()

rHORs_table = {}
with open(file,'r') as f:
    while True:
        line = f.readline()[:-1]
        if not line:
            break
        header = line
        seq = f.readline()[:-1]
        items = header.split(' ')
        pattern = items[0].split('::')[0][1:]
        if pattern != target_pattern:
            continue
        anno = items[1].split('::')
        rHor = anno[1][5:].split('_')
        if len(rHor) not in dis_table.keys():
            dis_table[len(rHor)] = 1
        else:
            dis_table[len(rHor)] += 1
        # print(header)
        for i in rHor:
            if i not in rHORs_table.keys():
                rHORs_table[i] = 1
            else:
                rHORs_table[i] += 1
mindis = sorted(list(dis_table.keys()))

final_dis_table = {}
for i in mindis:
    if i < 30:
        final_dis_table[i] = dis_table[i]
    else:
        if 30 not in final_dis_table.keys():
            final_dis_table[30] = dis_table[i]
        else:
            final_dis_table[30] += dis_table[i]
print(final_dis_table) # bar values
mindis = sorted(list(final_dis_table.keys()))
x = range(len(mindis))
y = []
tick_label = []
for i in mindis:
    y.append(final_dis_table[i])
    tick_label.append(i)

import numpy as np
import matplotlib.pyplot as plt
bar_width = 0.3
plt.figure(figsize=(10,8))
plt.bar(x, y, tick_label=tick_label, width=bar_width)
plt.savefig(outfile)
plt.close()
```

**Comment by duhuipeng** [comment]
Dear author
What is the code command？
I'm under this out_hor.normal.fa file 
![image](https://user-images.githubusercontent.com/58722433/206709009-999becaf-edb2-4642-b7d2-bd10c5288ab5.png)
Why my command line generation doesn't generate results
My code is as follows：
python3 barplot.py 
my result as follow:
![image](https://user-images.githubusercontent.com/58722433/206708919-659a2aa1-99af-4f51-ac66-551be8f30466.png)

**Comment by duhuipeng** [comment]
Dear author
If I can clearly see the regular HOR, shall I set word and window as the length of HOR？
How do I set these parameters if there is no apparent regularity of HOR？
![image](https://user-images.githubusercontent.com/58722433/206717029-18fe3241-3237-4119-9b3c-30988f70fc3c.png)
![image](https://user-images.githubusercontent.com/58722433/206717220-eda60391-ae84-4697-90dc-41a9909a2f69.png)
This is my result under different Windows，How should an indicator selection be made to determine which one is more suitable

Best
HuipengDu
