### ISSUE TITLE
HiCAT

### ISSUE THREAD

**Issue by duhuipeng** [xjtu-omics/HiCAT#2]
Dear author

I followed up on the question you turned off, but I didn't get a response from you,If you read this message, look forward to your response to the closed question as before。

Best
Huipengdu

**Comment by 865699871** [comment]
According to your question, the code is for CHM13 CEN1 and the pattern is R3L6 (target_pattern = 'R3L6').
If you want to use it in new out_hor.normal.fa, you need to **change the target_pattern based on your file.** 
The Dotplot word length in our manuscript is 10. You can change it between 10 to 20 based on your data. And the region in your Dotplot is too large. We only visualized three or four HOR units in our manuscript.
