### ISSUE TITLE
how to determine monomer sequence

### ISSUE THREAD

**Issue by slbai01** [xjtu-omics/HiCAT#4]
Hi,

How do I obtain centromeric monomer sequences if I am studying a species other than humans and Arabidopsis for which monomer sequences are known? Do you have a good suggestion?

Best wishes,

Shenglong

**Comment by 865699871** [comment]
Hi, Shenglong, you can try TRF (Tandem Repeat Finder). It can detect tandem repeats in genome and report the regions and unit consensus sequences in *.dat file. The consensus sequence of  tandem repeat unit can be used as monomer template.
