### ISSUE TITLE
The usage of HICAT

### ISSUE THREAD

**Issue by maypoleflyn** [xjtu-omics/HiCAT#5]
We are conducting some analysis about plant centromeres and found that you published a great tool "HICAT". However, we are confused with the input (monomer template) of HICAT and want your help. Do you have any suggestions about how to generate the monomer template file for a newly assembled genome?

**Comment by yangxiaofeill** [comment]
Hello,

     Please see this reply.
     https://github.com/xjtu-omics/HiCAT/issues/4#issuecomment-1501719749

Best
Xiaofei

**Comment by maypoleflyn** [comment]
Thanks very much for your reply. I know that the TRF can generate the monomers, however, the software will generate so many results, and should we feed all raw the results to the software?  I wonder if I can cluster the monomers using cd-hit and select the highest-occurrence monomer sequences for the software. Besides, I could not find the monomer temple files that you used in the paper. Did you use the CEN180 sequences as the monomer temple file only? I am still confused. I suggest that you can provide a detailed manual if possible, which will definitely benefit the widely usages of the software.

**Comment by 865699871** [comment]
1. Yes, you need cluster the monomer results in TRF and selected one as the template.
2. CEN180 that we used is: AAAAGCCTAAGTATTGTTTCCTTGTTAGAAGATACAAAGACAAAGACTCATATGGACTTCGGCTACACCATCAAAGCTTTGAGAAGCAAGAAGAAGCTTGGTTAGTGTTTTGGAGTCAAATATGACTTGATGTCATGTGTATGATTGAGTATAACAACTTAAACCGCAACCGGATCTT
We use CEN180 as monomer templet file only. 
4. We provided the detail manual in README, only need centromere sequence (tandem repeat sequence in fasta format) and monomer templet file (in fasta format). We do not limit the way users can obtain monomer template and TRF is one of them. But we will provide a pipline for obtaining templet in the future.

**Comment by 865699871** [comment]
You can find the input format in testdata. Human and plants are same. Thank you for considering our HiCAT. If you still have any questions about the input, you can also send me an e-mail ([gaoxian15002970749@163.com](mailto:gaoxian15002970749@163.com)).
