### ISSUE TITLE
Erro in running visualization.py

### ISSUE THREAD

**Issue by reddeery** [xjtu-omics/HiCAT#6]
Hi, 
I used the testdata to generate output, but when I used the visualization.py, I encountered a probleme like this:
```
Traceback (most recent call last):
  File "/home/data/ycy/tmp/HiCAT/visualization.py", line 490, in <module>
    main()
  File "/home/data/ycy/tmp/HiCAT/visualization.py", line 483, in main
    getResult(base_sequence, result_dir, similarity, show_hor_number, show_hor_min_repeat_number)
  File "/home/data/ycy/tmp/HiCAT/visualization.py", line 357, in getResult
    pattern_file = outdir + '/out_final_hor' + similarity + '.xls'  # 存在更新
TypeError: can only concatenate str (not "NoneType") to str
```
Although I try to used different method to install the HiCAT, including using xjtuomics-channel and take advantage of the requirements.txt, the proble still occur.  So what should I do to avoid the problem? Thanks.

**Comment by 865699871** [comment]
I cannot determine where the problem is only based on the error log. 
I think it may be due to the input. Can you provide more information about your input or you can send me on e-mail (gaoxian15002970749@163.com)
