### ISSUE TITLE
HiCAT takes a monomer template and a centromere DNA sequence as inputs

### ISSUE THREAD

**Issue by ZhouTaoWang** [xjtu-omics/HiCAT#7]
How to get monomer template and a centromere DNA sequence? Thank you!

**Comment by 865699871** [comment]
You can find the answer in our previous reply. #4 
Determine centromere sequence need a systematic work. 
Functional centromere is determined based on CENH3 chip-seq. 
The centromere sequence of most animals and plants are huge tandem repeat, so you can try TRF.
This review may help you know more about centromere (PMID: 32035948).

**Comment by colindaven** [comment]
I have also been trying to find centromeres in various plant genomes.

Practically, I found running Centrominer from https://github.com/aaranyue/quarTeT to be very good. Sometimes it can find centromeres automatically.

However sometimes Centrominer fails (basically picks telomeres as centromeres), but you can still take the `TRF` repeats in GFF3 format from the directory TRgff, `cat `them together, and manually select a better centromere candidate using the `gff3 `in the tool `JBrowse `for example. You can use peaks from the browser TRF track to estimate centromere location.
