### ISSUE TITLE
can't visualize output of hicat

### ISSUE THREAD

**Issue by PengfeiInTuebingen** [xjtu-omics/HiCAT#8]
Dear developer,
I successfully installed this by conda and I also test this tool using the test data you provided, I got the output like those: 
[$]~>  ls HiCAT_out
final_decomposition.tsv      out_all_layer4.xls   out_cluster_3.xls    out_final_hor3.xls      out_monomer_seq_3.xls  out_top_layer12.xls
final_decomposition_alt.tsv  out_all_layer5.xls   out_cluster_4.xls    out_final_hor4.xls      out_monomer_seq_4.xls  out_top_layer2.xls
final_decomposition_raw.tsv  out_all_layer6.xls   out_cluster_5.xls    out_final_hor5.xls      out_monomer_seq_5.xls  out_top_layer3.xls
input_fasta.1.fa             out_all_layer7.xls   out_cluster_6.xls    out_final_hor6.xls      out_monomer_seq_6.xls  out_top_layer4.xls
log.txt                      out_all_layer8.xls   out_cluster_7.xls    out_final_hor7.xls      out_monomer_seq_7.xls  out_top_layer5.xls
out                          out_all_layer9.xls   out_cluster_8.xls    out_final_hor8.xls      out_monomer_seq_8.xls  out_top_layer6.xls
out_all_layer0.xls           out_block.sequences  out_cluster_9.xls    out_final_hor9.xls      out_monomer_seq_9.xls  out_top_layer7.xls
out_all_layer1.xls           out_cluster_0.xls    out_final_hor0.xls   out_monomer_seq_0.xls   out_pre_merge.xls      out_top_layer8.xls
out_all_layer10.xls          out_cluster_1.xls    out_final_hor1.xls   out_monomer_seq_1.xls   out_statistics.xls     out_top_layer9.xls
out_all_layer11.xls          out_cluster_10.xls   out_final_hor10.xls  out_monomer_seq_10.xls  out_top_layer0.xls     stringdecomposer.log
out_all_layer12.xls          out_cluster_11.xls   out_final_hor11.xls  out_monomer_seq_11.xls  out_top_layer1.xls
out_all_layer2.xls           out_cluster_12.xls   out_final_hor12.xls  out_monomer_seq_12.xls  out_top_layer10.xls
out_all_layer3.xls           out_cluster_2.xls    out_final_hor2.xls   out_monomer_seq_2.xls   out_top_layer11.xls

When I want to  visualize those results by visualization.py, I got the error: 
[$]~>  python visualization.py -r HiCAT_out/
Traceback (most recent call last):
  File "/ebio/abt5_projects/3D_genome_of_brown_algae/data/software/HiCAT/visualization.py", line 490, in <module>
    main()
  File "/ebio/abt5_projects/3D_genome_of_brown_algae/data/software/HiCAT/visualization.py", line 483, in main
    getResult(base_sequence, result_dir, similarity, show_hor_number, show_hor_min_repeat_number)
  File "/ebio/abt5_projects/3D_genome_of_brown_algae/data/software/HiCAT/visualization.py", line 357, in getResult
    pattern_file = outdir + '/out_final_hor' + similarity + '.xls'  # 存在更新
TypeError: can only concatenate str (not "NoneType") to str
do you have any idea about this?
Best,
PF

**Comment by 865699871** [comment]
Hi, thank you for using HiCAT. 
HiCAT default output the result of similarity with the largest HOR coverage in ./out  .

We also provide additional script ’visualization.py‘ to visualize other similarity.
For example, 0 represents 0.94, 1 represents 0.945 and 2 represents 0.95 in default.
Except for ' -r ./HiCAT_out ', you need to add ' -s ' with a number to select which similarity result you want to visualize. 
For example, ' python visualization.py -r ./HiCAT_out -s 0 ' for parameter similarity=0.94.

Other parameter 
-sp represent the number of top HORs. default is 5.
-sn is the minimum repeat number of HOR. default is 10.

**Comment by 865699871** [comment]
The HOR coverage of different similarity is in ./HiCAT_out/out/sort_statistics.xls.
