### ISSUE TITLE
how to get monomer_template  

### ISSUE THREAD

**Issue by markme123** [xjtu-omics/HiCAT#9]
您好，我们在使用HICAT 软件时有一点疑问。输入序列需要 monomer_template。这种monomer_template能称为吗 basic repeating unit 。我在github 看到使用trf 预测出的 repeat unit ,寻找他们的共有片段作为 monomer_template，但是repeat unit 长短差异很大，我应该筛选什么样repeat unit呢。或者说monomer_template 一般建议多长呢。筛选长度之后应该怎么确定共有片段呢，用全局比对吗

**Comment by 865699871** [comment]
单体模板可以称为基本重复单元。
一般来说着丝粒串联重复是基因组中最大的，一些工具或者研究也是这样预测的。
但是在一些复杂的基因组中不一定，最可靠的方式是用CENH3蛋白抗体的chip-seq确定功能着丝粒，所以如果有早期基于chipseq的相关研究最好，很多模式物种或者作物有一些研究。
trf确实有很多不同长度的输出，根据先前研究着丝粒串联重复单元通常在100-400bp之间，参考PMID: 32035948这篇文章，里面介绍了相关研究背景。
确定模板之后可以通过全局比对确定片段。
